<?php
include_once __DIR__ . '/../../../../vendor/autoload.php';
use Lop\Api\LopDomainClient;
use Lop\Api\Request\LCP_00065267\WaybillJosServiceReceiveOrderInfoLopRequest;
use Lop\Api\Domain\LCP_00065267\WaybillJosService\TransExtendedDTO;
use Lop\Api\Domain\LCP_00065267\WaybillJosService\WaybillCouponDTO;
use Lop\Api\Domain\LCP_00065267\WaybillJosService\LordGiftWaybillRelationDTO;
use Lop\Api\Domain\LCP_00065267\WaybillJosService\ProductDetailDto;
use Lop\Api\Domain\LCP_00065267\WaybillJosService\WaybillDTO;
use Lop\Api\Domain\LCP_00065267\WaybillJosService\ProductAddedServiceDTO;
use Lop\Api\Domain\LCP_00065267\WaybillJosService\CustomerBoxDTO;
use Lop\Api\Plugin\Factory\HmacPluginFactory;
use Lop\Api\Plugin\Factory\OAuth2PluginFactory;
use Lop\Api\Plugin\DomainHttpParam;
//测试demo
$client = new LopDomainClient("SERVER_URL");
$request = new WaybillJosServiceReceiveOrderInfoLopRequest();
            $waybillDTO = new WaybillDTO();
                                $waybillDTO->setJosPin("123");
                                            $waybillDTO->setAppKey("89dc94e5efc841858e39539b131a6712");
                                            $waybillDTO->setSource("JOS");
                                            $waybillDTO->setSalePlat("0010001");
                                            $waybillDTO->setCustomerId(0);
                                            $waybillDTO->setCustomerCode("010K00001");
                                            $waybillDTO->setCustomerName("test");
                                            $waybillDTO->setOrderId("test");
                                            $waybillDTO->setThrOrderId("test");
                                            $waybillDTO->setSenderName("张三");
                                            $waybillDTO->setSenderAddress("北京市大兴区亦庄经济开发区荣京中路19号朝林广场A座21层");
                                            $waybillDTO->setSenderTel("test");
                                            $waybillDTO->setSenderMobile("test");
                                            $waybillDTO->setSenderPostcode("test");
                                            $waybillDTO->setReceiveName("李思");
                                            $waybillDTO->setReceiveAddress("北京市大兴区亦庄经济开发区荣京中路19号朝林广场A座21层");
                                            $waybillDTO->setReceiveTel("test");
                                            $waybillDTO->setReceiveMobile("test");
                                            $waybillDTO->setProvinceId(0);
                                            $waybillDTO->setProvince("test");
                                            $waybillDTO->setCityId(0);
                                            $waybillDTO->setCity("test");
                                            $waybillDTO->setCountyId(0);
                                            $waybillDTO->setCounty("test");
                                            $waybillDTO->setTownId(0);
                                            $waybillDTO->setTown("test");
                                            $waybillDTO->setPostcode("test");
                                            $waybillDTO->setPickMethod("test");
                                            $waybillDTO->setPickAddress("test");
                                            $waybillDTO->setPickContract("test");
                                            $waybillDTO->setPickContractTel("test");
                                            $waybillDTO->setPickContractMobile("test");
                                            $waybillDTO->setAreaProvId(0);
                                            $waybillDTO->setAreaCityId(0);
                                            $waybillDTO->setPackageCount(0);
                                            $waybillDTO->setWeight(1);
                                            $waybillDTO->setVloumLong(0);
                                            $waybillDTO->setVloumWidth(0);
                                            $waybillDTO->setVloumHeight(0);
                                            $waybillDTO->setVloumn(1000);
                                            $waybillDTO->setSelfPrintWayBill(0);
                                            $waybillDTO->setDescription("test");
                                            $waybillDTO->setGoodsMoney(0);
                                            $waybillDTO->setCollectionValue(0);
                                            $waybillDTO->setCollectionMoney(0);
                                            $waybillDTO->setGuaranteeValue(0);
                                            $waybillDTO->setGuaranteeValueAmount(0);
                                            $waybillDTO->setPackageRequired("test");
                                            $waybillDTO->setSignReturn(0);
                                            $waybillDTO->setAging(0);
                                            $waybillDTO->setTransType(0);
                                            $waybillDTO->setPType("test");
                                            $waybillDTO->setShopCode("test");
                                            $waybillDTO->setDeliveryTime("test");
                                            $waybillDTO->setOrderSendTime("test");
                                            $waybillDTO->setGoodsType(0);
                                            $waybillDTO->setOrderType(0);
                                            $waybillDTO->setOrderStatusId(0);
                                            $waybillDTO->setOrgId(0);
                                            $waybillDTO->setSortingCenterId(0);
                                            $waybillDTO->setSiteType(0);
                                            $waybillDTO->setSiteId(0);
                                            $waybillDTO->setSiteName("test");
                                            $waybillDTO->setRoad("test");
                                            $waybillDTO->setWarehouseCode("test");
                                            $waybillDTO->setRemark("test");
                                            $waybillDTO->setExtendField1("test");
                                            $waybillDTO->setExtendField2("test");
                                            $waybillDTO->setExtendField3("test");
                                            $waybillDTO->setExtendField4(0);
                                            $waybillDTO->setExtendField5(0);
                                            $waybillDTO->setIdNumber("test");
                                            $waybillDTO->setAddedService("test");
                                            $waybillDTO->setBillType(0);
                                            $waybillDTO->setStoreType("test");
                                            $waybillDTO->setCky2(0);
                                            $waybillDTO->setStoreId(0);
                                            $waybillDTO->setReturnType(0);
                                            $waybillDTO->setClientId(0);
                                            $waybillDTO->setShipmentStartTime(date_create());
                                            $waybillDTO->setShipmentEndTime(date_create());
                                            $waybillDTO->setPickupSign("test");
                                            $waybillDTO->setBussinessModel(0);
                                            $waybillDTO->setHalfReceive(0);
                                                                $waybillDTO->setLordGiftType(0);
                                                                $waybillDTO->setPickUpStartTime(date_create());
                                            $waybillDTO->setPickUpEndTime(date_create());
                                            $waybillDTO->setPickUpRemark("test");
                                            $waybillDTO->setDeliveryPromiseTime(date_create());
                                            $waybillDTO->setOrderSubmitTime(date_create());
                                            $waybillDTO->setLogisticMode(0);
                                                                $waybillDTO->setSenderCompany("test");
                                            $waybillDTO->setReceiveCompany("test");
                                            $waybillDTO->setUserPin("test");
                                            $waybillDTO->setSenderProvinceId(0);
                                            $waybillDTO->setSenderProvince("test");
                                            $waybillDTO->setSenderCityId(0);
                                            $waybillDTO->setSenderCity("test");
                                            $waybillDTO->setSenderCountyId(0);
                                            $waybillDTO->setSenderCounty("test");
                                            $waybillDTO->setSenderTownId(0);
                                            $waybillDTO->setSenderTown("test");
                                            $waybillDTO->setSenderIdNumber("test");
                                            $waybillDTO->setSenderIdType(0);
                                            $waybillDTO->setGoods("test");
                                            $waybillDTO->setGoodsCount(0);
                                            $waybillDTO->setFreight(0);
                                            $waybillDTO->setPromiseTimeType(0);
                                                                $waybillDTO->setWaybillChannel("test");
                                            $waybillDTO->setUnpackingInspection("test");
                                                                $waybillDTO->setFileUrl("https://cloud.jdl.cn");
                                            $waybillDTO->setPickUpDetailType(0);
                                            $waybillDTO->setPickupSiteId(0);
                                                                    $request->setWaybillDTO($waybillDTO);
                $lopOauthPlugin = OAuth2PluginFactory::produceLopPlugin($client->getServerUrl(),"appKey", "appSecret", "refreshToken");
        $request->addLopPlugin($lopOauthPlugin);
    //参数校验
$request->check();
$resp = $client->execute($request);
echo json_encode($resp,JSON_UNESCAPED_UNICODE);
echo PHP_EOL;
